### PR TITLE
All routes showing in IndexHandler

### PR DESCRIPTION
**Pull request by nmaggioni**
As per #9, I thought I could help as I liked that feature as well.
- [X] Make all routes show up (not only GETs)
- [X] Update tests

What about displaying the method of each route? What could your suggested strategy be?
This structure came up on top of my mind:

``` json
{
  "hello_url": {
    "method": "GET",
    "path": "/hello/:name"
  },
  "user_logout_url": {
    "method": "POST",
    "path": "/user/logout"
  }
}
```

Do I have the :green_apple: light to go on?

### CODE REVIEW

**Comment by bahlo** [comment]
Hi @nmaggioni, thank you for the PR!

I think your proposed format is not as visible as the existing one - maybe it'd be better to group them top-level like this?

```json
{
  "GET": {
    "hello_url": "/hello/:name",
    "foo_url": "/foo/:name"
  },
  "POST": {
    "bar_url": "/bar"
  }
}
```

@nmaggioni @zwerch  What do you think?

**Comment by nmaggioni** [comment]
Great idea, I'll work on it.

**Comment by nmaggioni** [comment]
As per [the official blog](https://blog.golang.org/go-maps-in-action#TOC_7) maps are tough to sort, but after extensive testing I found out that - even without explicit sorting - the final result seems to come through sorted anyway.

With the latest commit I get this output when calling `Index()` and writing it out to the JSON ResponseWriter:

```json
{
  "DELETE": {
    "delete_bucket": "/:bucket",
    "delete_bucket_key": "/:bucket/:key"
  },
  "GET": {
    "get_bucket_key": "/:bucket/:key",
    "list_all_buckets_and_keys": "/",
    "list_bucket_keys": "/:bucket"
  },
  "OPTIONS": {
    "help": "/"
  },
  "POST": {
    "set_bucket_key": "/:bucket/:key"
  },
  "PUT": {
    "set_bucket_key": "/:bucket/:key"
  }
}
```

All test are passing, tell me if there's something else left to do!

**Comment by nmaggioni** [comment]
Any news on this being merged?

**Comment by zwerch** [comment]
I like it, you can go ahead and merge @bahlo! 👍

**Pull request closed without merging**
